### ISSUE TITLE
As a user, I want to see a menu of game include guide, credit and play button so the players know what to do 

### ISSUE THREAD

**Issue by larycoder** [larycoder/USTH-SE-2019#11]
# Task
## Design: 
- [x]  Design [diagram](https://github.com/larycoder/USTH-SE-2019/blob/project/group-8/menu/design_diagram/Menu.png) of mechanism of menu ([reference](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/2042a4ecd013433ab5a1c552560617f4/aa7bc2e78d52498fa9d3809c0526b390/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%40c351206120604136850df56ccfa7acc9))
- [x]  Choose pattern design => using [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) ([reference](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/7d0289438e6a4d6491f2b0adbc48763a/ba2a508c074840bca101d4d010d5c8c2/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%4067d8c851d0de4be693d14ed493b99af6))
- [x]  Create object and viewer within [html file](https://github.com/larycoder/USTH-SE-2019/blob/project/group-8/menu/demo.html)
- [x]  Design [controller mechanism](https://github.com/larycoder/USTH-SE-2019/blob/project/group-8/menu/endGame.html) for menu
- [x] Design API of menu => choose reasonable id of element in html for merging to whole system ([reference](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/2042a4ecd013433ab5a1c552560617f4/d8857d39fd5c418faa941c14a5849864/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%402c88df1a38e14875bb6fd35bee47b364))
## Testing:
- [x]  review the code => (reviewer: Chu Hiep ) it work good and mechanism easy to understand. this is image of [result1](https://github.com/larycoder/USTH-SE-2019/blob/project/group-8/test/resultTesting/menu_test_part1.png) and [result2](https://github.com/larycoder/USTH-SE-2019/blob/project/group-8/test/resultTesting/menu_test_part2.png)
    - [x]  Check black box testing => fail because not yet find out suitable test framework (high prior: mocha) ([reference](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/5692eb185917488e9f97c9f346fe932d/ff578d1b33004ac68708a25877142c5f/2?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%4031bc79511c6c4085b42a0d2fa67d6405))
    - [x] Design white Box test => 100 coverage ( testing by hand - reviewer: Chu Hiep ) ([reference](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/5692eb185917488e9f97c9f346fe932d/7697250165fa41039fb5f0c764cbe186/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%4063796ce1fa8b4550b3b69e1a05ff2853))
    - [x] fix linter of code and check code smell in [here](https://github.com/larycoder/USTH-SE-2019/commit/2f9cfd1d453fc59556bc128ca33eac92b95c5d05#diff-e9448571db35afbef82ffe60091daab0) ([reference](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/a58ebf5981e4464c93bccdbc69269898/ee6367de9a534328bd673e35504c7249/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%4022bc46d064d04877b845da9f3bfad9e0))
## low-level design
- [x]  Build the [code](https://github.com/larycoder/USTH-SE-2019/tree/project/group-8/menu) then [merge](https://github.com/larycoder/USTH-SE-2019/commit/fd6475d8b1e40ff5f8dc0796513b506a7a4686da#diff-7bf8f8d54e2014e192947f464cb8db16) to whole system

(Update 2019-03-21)
